//version: 1707058017

plugins {
    id 'com.github.ElytraServers.elytra-conventions' version "v1.1.0"
    id 'com.gtnewhorizons.gtnhconvention'
}

jar {
    archiveVersion = project.version + "+" + project.property("elytra.manifest.version")
}

tasks.register("copyJarWithoutSuffix", Copy) {
    dependsOn tasks.named("reobfJar")
    def jarTask = tasks.named("jar").get()
    from(layout.buildDirectory.file("libs/${jarTask.archiveBaseName.get()}-${jarTask.archiveVersion.get()}.jar"))
    into layout.buildDirectory.dir("libs")
    rename { "${project.property("modId")}.jar" }
}

tasks.named("build") {
    finalizedBy tasks.named("copyJarWithoutSuffix")
}
